### ISSUE TITLE
Failed to resolve your library.

### ISSUE THREAD

**Issue by aftabsikander** [VEINHORN/android-tagview#6]
I am getting this error "Failed to resolve: com.veinhorn.tagview:library:1.0.3@aar". I am getting this error from today. As in past It was working. I even checked the maven to see is the link valid or not. I was unable to find your repo on maven, I believe you have deleted the repo.
Do correct me if I am wrong.

**Comment by aftabsikander** [comment]
I have fixed it, As i was looking at your code, I saw you have updated your application version code. but you deleted the old version from maven and update the latest project. I even saw you have created a ticket # 5 "Update readme for 1.0.4 ver". So I just change this line and it fixed my issue.

Old dependency link:
compile 'com.veinhorn.tagview:library:1.0.3@aar'

New dependency link:
compile 'com.veinhorn.tagview:library:1.0.4'

**Comment by VEINHORN** [comment]
I updated README. Thank you for your feedback.
