### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by davidmind** [VEINHORN/android-tagview#9]
Hi, @VEINHORN 
I am a graphics designer, I will like to know if you want me to create a new logo for your project

**Comment by VEINHORN** [comment]
Hi @davidmind . It would be nice if you can provide logo. :+1: Thanks.

**Comment by davidmind** [comment]
Ok, I will go and make a sketch and give you feed back

**Comment by VEINHORN** [comment]
@davidmind ok, much thanks :+1:

**Comment by davidmind** [comment]
Hi, @VEINHORN sorry it is coming late. I was a little bit busy this week.
This is what I come up with after making my sketch.


![tagview.png](https://cdn.steemitimages.com/DQmXefrjboPhxW557Mm5ZtT41N6Nud9QomNEuZpmfui5yz6/tagview.png)

**Comment by davidmind** [comment]
@VEINHORN are you there?

**Comment by VEINHORN** [comment]
Hi @davidmind . Nice logo. :+1:  Can you please update README and add logo?

**Comment by davidmind** [comment]
Ok, which color did you want me to use for the readme?

**Comment by davidmind** [comment]
@VEINHORN am still waiting for your response, which of the following color did you like most
![1557084598230.jpg](https://cdn.steemitimages.com/DQmckECTiMDowC7G6z8xakkvGg4iftoiLjpqq4fCvvDkAey/1557084598230.jpg)

**Comment by VEINHORN** [comment]
@davidmind I like most second color. :)

**Comment by davidmind** [comment]
Ok, i will work on it as soon as possible

**Comment by davidmind** [comment]
@VEINHORN i have created a pull request, this is the link to editable files [Here](https://drive.google.com/folderview?id=16fRguF-KWT6pNPVvITS0vF9WbCv7cjPS).
I have also create a pull request
